// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvWV0Hty_hSLb0lql11aEA5LhpWp_a0I0',
    appId: '1:1009004769830:web:515c823ae7e1618f45ace7',
    messagingSenderId: '1009004769830',
    projectId: 'fashion-store-15952',
    authDomain: 'fashion-store-15952.firebaseapp.com',
    storageBucket: 'fashion-store-15952.firebasestorage.app',
    measurementId: 'G-X4TR01LNSB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFVqwlqCdfv1PvpRXMsWiTjRQfJI12Oo8',
    appId: '1:1009004769830:android:3018a9e06bd2109a45ace7',
    messagingSenderId: '1009004769830',
    projectId: 'fashion-store-15952',
    storageBucket: 'fashion-store-15952.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6-L7fxKlIZqcR3W7QflMywdhntokYFoo',
    appId: '1:1009004769830:ios:7970cfcb3ad9ad6045ace7',
    messagingSenderId: '1009004769830',
    projectId: 'fashion-store-15952',
    storageBucket: 'fashion-store-15952.firebasestorage.app',
    iosBundleId: 'com.example.fashionStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6-L7fxKlIZqcR3W7QflMywdhntokYFoo',
    appId: '1:1009004769830:ios:7970cfcb3ad9ad6045ace7',
    messagingSenderId: '1009004769830',
    projectId: 'fashion-store-15952',
    storageBucket: 'fashion-store-15952.firebasestorage.app',
    iosBundleId: 'com.example.fashionStore',
  );

}

  // "type": "service_account",
  // "project_id": "fashion-store-15952",
  // "private_key_id": "20c152941a7fd5ef26eefe4ecf74cce0f46e69fe",
  // "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQClavxQWEWDnV7Z\nVBFeF9jwlGaa3mo7C+mwBadO1wHVQQoAnKif4gT/Mqscr5epE6UQQPn9i+SXhWrd\nX0ejtpDWzBovsZU20o0GUwmK/WMM6ie3jFeY5sOoBhBEwU6TL25MS2/nfnexmjkg\nEoGQ3K2f4miayNkisLnX11onwHrWptHDUkE+4uhNZqoUgzlhpyz39NLUezfg2Y+3\nteAm1VuIOPeaqkN65Iawih5TMjksr0DD8XhPQq+m0BKqa1itIRF8JGcNhlPf3qgj\niOCq4N3xd7W+AjA6AtFM5yPMUFQh2H01e6/MFCZZiOZBaylwJlTxuw8c0RLNMTZd\noCzzFyZxAgMBAAECggEACPFSuKk9ANOGKCuiULrrUH5FWcQCbDTFqm1z0RBQmg3N\nE6FkgFhAuucrVv6rLUnRl6JboXhpoENnNpaLEe+xvtsD42YvUepqE1hz4J64Nx+F\njCe7KJn5I+FICd+FdvGOffNqFlLA98oFopU9ie5UOJuN2ihXjMePFHsg9ZszSN1f\noWLC424pk7XKrGb1/lzXGz8vaycPbMCfOVV3+RfD29t7/9kZ/PO62l8toacPWY4h\n9rCgvvQKMcX2RtvaElSKCDPQt550ms42bI5uCMMNtvs0CFcR111bp0TpuM3+CdpO\nCTkTftCAOItAKfe0up8HvpjQscTRRYbCtdI5koe0EQKBgQDTtZOaOXBoNEll4wx9\nZlSwCVbvOKjMWbhjX9kXWiE5pEL3en6OGjommhQ+6TW0+t05yUG5MreBaN9Oz1uu\nzZjpajvMDqoEU633skqeGuKDxAwf28DwLRdJ38uMmGMcbXlLDZbc90exnevEuj3c\nbFAIII8lBJABb7kXA6RKp9YhbQKBgQDIBjOvmxWB6eeylcfGpvCxYg81mAez3mkR\nnKvq74yvP7M/QK2ill8ZfLMAFedYb5BPUciSIHX/y58c9ZHM1N3AsQaGXxeLNiXD\nGdM1G/II0MuKESQeRqMzRqCKbx/OuqIcuuzKvx9UgPsVchZ9eXxjYzsjo9BrTEUq\nXU/15I86lQKBgHWV9FVEcdpusBWW9ejwXTko9tAHeDmH25HWOo1t0eZiBY/OyVvD\n1Wh7S6NlhB7w9s6RqZ9jO+j0hpMPOKzuJHAAQRYlTuj4UTeyHx+Rbx4gVVucgpzj\nbnvpgPSl7uZrJ2M4OQKhlYBhZgHuL02uGwVokBjPX+xsUTEnJKkSbyxBAoGBALsM\nwazIFBbHC7r/QjDM0GywzJRLtXhI1mx33HT4ytDfetn9u+I9SHVnHWVJFmym94aV\nbkDoRjCM1CCarFul/DFD2lwx9KxkWG/YaKBTn8UKrCxS1znQyLEcrOiH/nCuKwc+\n7kyy6bN2Ylatt8ZioyW2GAm+GRsd2dhCJpJFyIL5AoGBAMX4mIzMZMhBMZ2izF/R\npOLtLwbihMhgfc5YV7B5gSEoH2OMI3fGIJ9Sb/qMN+jMIb8l0fMj5mB7S6hmgihD\n+KB5QnwPTb5H3WYDyjoIDDm/1DZc7EdAPN0QmlQn1yD7OzutOyf3nxlc5JdsGERO\nBJeuT3vpTCKBKp21myQnpi28\n-----END PRIVATE KEY-----\n",
  // "client_email": "firebase-adminsdk-fbsvc@fashion-store-15952.iam.gserviceaccount.com",
  // "client_id": "115479982354743259281",
  // "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  // "token_uri": "https://oauth2.googleapis.com/token",
  // "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  // "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40fashion-store-15952.iam.gserviceaccount.com",
  // "universe_domain": "googleapis.com"